In [1]:
import numpy as np

In [2]:
np.array([1,2,3,])

array([1, 2, 3])

In [3]:
np.array([[1,2,3],[9,8,7,]])

array([[1, 2, 3],
       [9, 8, 7]])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.array([1,2.0,3])

array([1., 2., 3.])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.eye(5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.eye(5,k=4)

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [21]:
np.eye(5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [23]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [24]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
a = np.array([[5,10,15],[20,25,20]])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Size of array : 6
Manual determination of size of array : 6

In [27]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [29]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [33]:
b = a.flatten()
b

array([1., 1., 1., 1.])

In [34]:
c = a.ravel()
c

array([1., 1., 1., 1.])

In [1]:
import pandas as pd

In [4]:
data=pd.read_csv("employees_120.csv")
data

     emp_id      emp_name department  salary  manager_id   join_date  store_id
0         1    Employee_1         HR   31979        13.0  2018-06-01         9
1         2    Employee_2         IT   86558        17.0  2017-12-22         4
2         3    Employee_3         HR   50227         7.0  2020-10-19        13
3         4    Employee_4    Finance   64071        15.0  2019-04-26         2
4         5    Employee_5         HR   82866         9.0  2020-10-06        17
..      ...           ...        ...     ...         ...         ...       ...
115     116  Employee_116         HR   57602         2.0  2022-02-12        20
116     117  Employee_117      Sales   52516        15.0  2017-07-23         2
117     118  Employee_118         IT   62346         7.0  2016-08-15        15
118     119  Employee_119    Support   92494         5.0  2016-10-01        20
119     120  Employee_120    Finance   53795         NaN  2020-04-04         3

[120 rows x 7 columns]

In [5]:
data.head(5)

   emp_id    emp_name department  salary  manager_id   join_date  store_id
0       1  Employee_1         HR   31979        13.0  2018-06-01         9
1       2  Employee_2         IT   86558        17.0  2017-12-22         4
2       3  Employee_3         HR   50227         7.0  2020-10-19        13
3       4  Employee_4    Finance   64071        15.0  2019-04-26         2
4       5  Employee_5         HR   82866         9.0  2020-10-06        17

In [6]:
data.tail(5)

     emp_id      emp_name department  salary  manager_id   join_date  store_id
115     116  Employee_116         HR   57602         2.0  2022-02-12        20
116     117  Employee_117      Sales   52516        15.0  2017-07-23         2
117     118  Employee_118         IT   62346         7.0  2016-08-15        15
118     119  Employee_119    Support   92494         5.0  2016-10-01        20
119     120  Employee_120    Finance   53795         NaN  2020-04-04         3

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      120 non-null    int64
 1   emp_name    120 non-null    object
 2   department  120 non-null    object
 3   salary      120 non-null    int64
 4   manager_id  116 non-null    float64
 5   join_date   120 non-null    object
 6   store_id    120 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 6.7+ KB

In [8]:
data.describe()

           emp_id        salary  manager_id    store_id
count  120.000000    120.000000  116.000000  120.000000
mean    60.500000  59564.325000   10.818966   10.466667
std     34.785054  20897.562296    5.792948    5.661210
min      1.000000  25162.000000    1.000000    1.000000
25%     30.750000  41021.000000    6.000000    6.000000
50%     60.500000  57596.500000   11.500000   10.500000
75%     90.250000  80565.000000   16.250000   15.000000
max    120.000000  94184.000000   20.000000   20.000000

In [13]:
data.loc[data["salary"]>20000]

     emp_id      emp_name department  salary  manager_id   join_date  store_id
0         1    Employee_1         HR   31979        13.0  2018-06-01         9
1         2    Employee_2         IT   86558        17.0  2017-12-22         4
2         3    Employee_3         HR   50227         7.0  2020-10-19        13
3         4    Employee_4    Finance   64071        15.0  2019-04-26         2
4         5    Employee_5         HR   82866         9.0  2020-10-06        17
..      ...           ...        ...     ...         ...         ...       ...
115     116  Employee_116         HR   57602         2.0  2022-02-12        20
116     117  Employee_117      Sales   52516        15.0  2017-07-23         2
117     118  Employee_118         IT   62346         7.0  2016-08-15        15
118     119  Employee_119    Support   92494         5.0  2016-10-01        20
119     120  Employee_120    Finance   53795         NaN  2020-04-04         3

[120 rows x 7 columns]

In [15]:
data.loc[0:7]

   emp_id    emp_name  department  salary  manager_id   join_date  store_id
0       1  Employee_1          HR   31979        13.0  2018-06-01         9
1       2  Employee_2          IT   86558        17.0  2017-12-22         4
2       3  Employee_3          HR   50227         7.0  2020-10-19        13
3       4  Employee_4     Finance   64071        15.0  2019-04-26         2
4       5  Employee_5          HR   82866         9.0  2020-10-06        17
5       6  Employee_6          HR   83279        17.0  2016-10-19         9
6       7  Employee_7          IT   47168         7.0  2017-11-03        14
7       8  Employee_8  Operations   80419        17.0  2015-02-20        20

In [14]:
data.iloc[0:7]

   emp_id    emp_name department  salary  manager_id   join_date  store_id
0       1  Employee_1         HR   31979        13.0  2018-06-01         9
1       2  Employee_2         IT   86558        17.0  2017-12-22         4
2       3  Employee_3         HR   50227         7.0  2020-10-19        13
3       4  Employee_4    Finance   64071        15.0  2019-04-26         2
4       5  Employee_5         HR   82866         9.0  2020-10-06        17
5       6  Employee_6         HR   83279        17.0  2016-10-19         9
6       7  Employee_7         IT   47168         7.0  2017-11-03        14

In [17]:
data["salary"].mean()

59564.325

In [18]:
data.isnull()

     emp_id  emp_name  department  salary  manager_id  join_date  store_id
0     False     False       False   False       False      False     False
1     False     False       False   False       False      False     False
2     False     False       False   False       False      False     False
3     False     False       False   False       False      False     False
4     False     False       False   False       False      False     False
..      ...       ...         ...     ...         ...        ...       ...
115   False     False       False   False       False      False     False
116   False     False       False   False       False      False     False
117   False     False       False   False       False      False     False
118   False     False       False   False       False      False     False
119   False     False       False   False        True      False     False

[120 rows x 7 columns]

In [19]:
data.isnull().sum()

emp_id        0
emp_name      0
department    0
salary        0
manager_id    4
join_date     0
store_id      0
dtype: int64

In [20]:
data.isnull().sum().sum()

4